'use client';
import {useCallback,useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {shrinkImage} from '@/lib/image-client';
import PhotoManager,{ClearAllPhotos} from '@/components/admin/PhotoManager';
import DesignEditor from '@/components/admin/DesignEditor';
import Keepsakes from '@/components/admin/Keepsakes';
import {StatusPill,logout} from './AdminEvents';
import type {Event,StatusCounts} from '@/lib/types';
type Tab='overview'|'submissions'|'design'|'settings';
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:init?.body instanceof FormData?undefined:{'Content-Type':'application/json'}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
export default function AdminDashboard({eventId}:{eventId:string}){const [event,setEvent]=useState<Event|null>(null);const [counts,setCounts]=useState<StatusCounts>({pending:0,approved:0,rejected:0});const [tab,setTab]=useState<Tab>('overview');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [origin,setOrigin]=useState('');const [qr,setQr]=useState('');
const load=useCallback(async()=>{try{const j=await api<{event:Event;counts:StatusCounts}>(`/api/admin/events/${eventId}`);setEvent(j.event);setCounts(j.counts)}catch(e){setError((e as Error).message)}},[eventId]);
useEffect(()=>{load();const iv=setInterval(load,5000);return()=>clearInterval(iv)},[load]);
useEffect(()=>{setOrigin(window.location.origin);QRCode.toDataURL(`${window.location.origin}/upload?event=${eventId}`,{width:480,margin:2}).then(setQr)},[eventId]);
function flash(m:string){setNotice(m);setTimeout(()=>setNotice(''),2500)}
async function run(fn:()=>Promise<unknown>,ok?:string){setError('');try{await fn();if(ok)flash(ok);await load()}catch(e){setError((e as Error).message)}}
const save=(patch:Partial<Event>,ok='Saved')=>run(()=>api(`/api/admin/events/${eventId}`,{method:'PATCH',body:JSON.stringify(patch)}),ok);
const pmFlash=useCallback((m:string,err?:boolean)=>{if(err)setError(m);else{setError('');flash(m)}},[]);
// Shrink first: Vercel rejects request bodies over 4.5 MB.
const uploadTarget=(f:File)=>run(async()=>{const fd=new FormData();fd.append('file',await shrinkImage(f,2400),'target.jpg');return api(`/api/admin/events/${eventId}/target`,{method:'POST',body:fd})},'Target image updated');
if(!event)return <main className="grid min-h-screen place-items-center bg-[#08090b] p-6 text-center"><div>{error?<><p className="text-red-300">{error}</p><a href="/admin" className="mt-4 inline-block text-sm underline">Back to events</a></>:<p className="text-zinc-500">Loading…</p>}</div></main>;
const guestUrl=`${origin}/upload?event=${eventId}`,wallUrl=`/wall?event=${eventId}`;const total=event.rows*event.columns;
return <main className="min-h-screen bg-[#08090b] p-6 md:p-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><a href="/admin" className="text-xs uppercase tracking-[.35em] text-zinc-500 hover:text-zinc-300">← All events</a><h1 className="mt-2 flex items-center gap-3 text-3xl font-semibold">{event.name}<StatusPill status={event.status}/></h1></div><div className="flex flex-wrap gap-2">{event.status!=='live'?<button onClick={()=>save({status:'live'},'Event is live')} className="rounded-full bg-[#d8ff3e] px-4 py-2 text-sm font-semibold text-black">Go live</button>:<button onClick={()=>save({status:'ended'},'Event ended')} className="rounded-full border border-red-400/40 px-4 py-2 text-sm text-red-300">End event</button>}<a className="rounded-full border border-zinc-700 px-4 py-2 text-sm" href={wallUrl} target="_blank">Open wall</a><a className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-black" href={`/upload?event=${eventId}`} target="_blank">Guest upload</a><button onClick={logout} className="rounded-full border border-zinc-700 px-4 py-2 text-sm">Log out</button></div></div>
{(error||notice)&&<p className={`mt-4 text-sm ${error?'text-red-300':'text-emerald-300'}`}>{error||notice}</p>}
<div className="mt-8 grid gap-4 lg:grid-cols-[220px_1fr]"><aside className="glass h-fit rounded-2xl p-2">{(['overview','submissions','design','settings'] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-left text-sm capitalize ${tab===x?'bg-white text-black':'text-zinc-400 hover:bg-zinc-900'}`}>{x==='submissions'?'Photos':x}{x==='submissions'&&counts.pending>0&&<span className="rounded-full bg-amber-400 px-2 text-xs font-semibold text-black">{counts.pending}</span>}</button>)}</aside>
<section className="glass min-h-[620px] rounded-2xl p-6">
{tab==='overview'&&<div><div className="mb-6"><Keepsakes event={event} onChanged={load}/></div><div className="grid gap-4 md:grid-cols-4"><Metric label="Filled" value={`${event.approved_count} / ${total}`}/><Metric label="Complete" value={`${Math.min(100,Math.round(event.approved_count/total*100))}%`}/><Metric label="Pending" value={`${counts.pending}`}/><Metric label="Rejected" value={`${counts.rejected}`}/></div>
{event.status==='live'&&!event.auto_approve&&<div className="mt-6 rounded-2xl border border-sky-400/30 bg-sky-400/5 p-5 text-sm text-sky-200">Moderation is on: new photos wait in <button onClick={()=>setTab('submissions')} className="underline">Photos → Waiting</button>{counts.pending>0?` (${counts.pending} waiting now)`:''} until you approve them. To send photos straight to the wall, turn on Auto approve in <button onClick={()=>setTab('settings')} className="underline">Settings</button>.</div>}
{event.status!=='live'&&<div className="mt-6 rounded-2xl border border-amber-400/30 bg-amber-400/5 p-5 text-sm text-amber-200">{event.status==='draft'?'Guests cannot upload yet. Add a target image in Settings, then press “Go live”.':'This event has ended. Guests can no longer upload.'}</div>}
<div className="mt-6 grid gap-6 md:grid-cols-[auto_1fr]">{qr&&<div className="w-fit rounded-2xl bg-white p-4"><img src={qr} alt="Event QR code" className="h-56 w-56"/><a href={qr} download={`qr-${event.name}.png`} className="mt-2 block text-center text-xs font-semibold text-black underline">Download QR</a></div>}<div><p className="text-sm text-zinc-400">Guest upload link</p><div className="mt-2 break-all rounded-xl bg-zinc-950 p-4 text-sm">{guestUrl}</div><button onClick={()=>{navigator.clipboard.writeText(guestUrl);flash('Link copied')}} className="mt-3 rounded-full border border-zinc-700 px-4 py-2 text-sm">Copy link</button><p className="mt-6 text-sm text-zinc-400">Big screen</p><div className="mt-2 break-all rounded-xl bg-zinc-950 p-4 text-sm">{origin}{wallUrl}</div><p className="mt-2 text-xs text-zinc-500">Open this on the display and press F (or double-click) for full screen: only the mosaic stays. It updates live.</p></div></div></div>}
{tab==='submissions'&&<PhotoManager eventId={eventId} counts={counts} onChanged={load} flash={pmFlash}/>}
{tab==='design'&&<DesignEditor event={event} onSave={(p,ok)=>save(p as Partial<Event>,ok)}/>}
{tab==='settings'&&<div className="grid gap-10"><Settings event={event} onSave={save} onTarget={uploadTarget}/><ClearAllPhotos eventId={eventId} eventName={event.name} onDone={load} flash={pmFlash}/></div>}
</section></div></div></main>}
function Settings({event,onSave,onTarget}:{event:Event;onSave:(p:Partial<Event>)=>void;onTarget:(f:File)=>void}){const [name,setName]=useState(event.name);const [msg,setMsg]=useState(event.final_message||'');const [goal,setGoal]=useState(event.goal??150);const [rows,setRows]=useState(event.rows),[cols,setCols]=useState(event.columns);const locked=event.approved_count>0;
return <div className="grid gap-8"><div><h3 className="font-semibold">Target image</h3><p className="mt-1 text-sm text-zinc-500">The picture the photos form at the end. Until you upload one, the wall uses the Micron logo.</p><div className="mt-4 flex flex-wrap items-center gap-4">{event.target_image_url?<img src={event.target_image_url} alt="Target" className="h-32 rounded-xl border border-zinc-800 object-cover"/>:<div className="grid h-32 w-48 place-items-center rounded-xl border border-dashed border-zinc-700 text-xs text-zinc-500">No image yet</div>}<label className="cursor-pointer rounded-full bg-white px-4 py-2 text-sm font-semibold text-black">Upload image<input type="file" accept="image/*" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)onTarget(f);e.target.value=''}}/></label></div></div>
<div className="grid gap-4 md:grid-cols-2"><Text label="Event name" value={name} onChange={setName}/><Text label="Message when the wall is complete" value={msg} onChange={setMsg}/></div>
<div className="max-w-xs"><Num label="Photos needed for the big picture" value={goal} onChange={setGoal} max={10000}/><p className="mt-2 text-xs text-zinc-500">When this many photos are on the wall, they rearrange by colour into the target image. Photos keep arriving afterwards.</p></div>
<p className="text-xs text-zinc-500">Colours, photo borders, sizes, spacing and animation are in the Design tab.</p>
<div><div className="grid gap-4 md:grid-cols-2"><Num label="Rows" value={rows} onChange={setRows} disabled={locked}/><Num label="Columns" value={cols} onChange={setCols} disabled={locked}/></div><p className="mt-2 text-xs text-zinc-500">{rows*cols} photos fill the wall.{locked&&' Grid size is locked because photos are already on the wall.'}</p></div>
<label className="flex items-center justify-between rounded-xl border border-zinc-800 p-4"><span><span className="block text-sm">Auto approve</span><span className="text-xs text-zinc-500">Photos go straight to the wall without review.</span></span><input type="checkbox" checked={!!event.auto_approve} onChange={e=>onSave({auto_approve:e.target.checked})} className="h-5 w-5"/></label>
<div><button onClick={()=>onSave({name,final_message:msg,goal,...(locked?{}:{rows,columns:cols})})} className="rounded-full bg-[#d8ff3e] px-5 py-2.5 text-sm font-semibold text-black">Save changes</button></div></div>}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-2xl border border-zinc-800 p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs text-zinc-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm"/></label>}
function Num({label,value,onChange,disabled,max=100}:{label:string;value:number;onChange:(v:number)=>void;disabled?:boolean;max?:number}){return <label><span className="text-xs text-zinc-500">{label}</span><input type="number" min="2" max={max} disabled={disabled} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm disabled:opacity-40"/></label>}
