'use client';
import {useEffect,useState} from 'react';
import type {Event} from '@/lib/types';
export async function logout(){await fetch('/api/admin/login',{method:'DELETE'});window.location.href='/admin/login'}
export default function AdminEvents(){const [events,setEvents]=useState<Event[]|null>(null);const [name,setName]=useState('');const [rows,setRows]=useState(25),[cols,setCols]=useState(30);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
useEffect(()=>{fetch('/api/admin/events').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setEvents(j.events)}).catch(e=>setError(e.message))},[]);
async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/admin/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,rows,columns:cols})});const j=await r.json();if(!r.ok){setError(j.error);setBusy(false);return}window.location.href=`/admin?event=${j.event.id}`}
return <main className="min-h-screen bg-[#08090b] p-6 md:p-10"><div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.35em] text-zinc-500">Control room</p><h1 className="mt-2 text-3xl font-semibold">Events</h1></div><button onClick={logout} className="rounded-full border border-zinc-700 px-4 py-2 text-sm">Log out</button></div>
<form onSubmit={create} className="glass mt-8 grid gap-4 rounded-2xl p-6 md:grid-cols-[1fr_120px_120px_auto] md:items-end"><label><span className="text-xs text-zinc-500">New event name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Annual Gala 2026" className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm"/></label><Num label="Rows" value={rows} onChange={setRows}/><Num label="Columns" value={cols} onChange={setCols}/><button disabled={!name.trim()||busy} className="rounded-xl bg-[#d8ff3e] px-5 py-3 text-sm font-semibold text-black disabled:opacity-40">{busy?'Creating…':'Create event'}</button><p className="text-xs text-zinc-500 md:col-span-4">{rows*cols} photos fill the wall. You can change this until the first photo is approved.</p></form>
{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}
<div className="mt-8 grid gap-3">{events===null&&!error&&<p className="text-sm text-zinc-500">Loading…</p>}{events?.length===0&&<p className="text-sm text-zinc-500">No events yet. Create one above.</p>}{events?.map(ev=><a key={ev.id} href={`/admin?event=${ev.id}`} className="glass flex items-center justify-between rounded-2xl p-5 hover:border-zinc-600"><div><p className="font-medium">{ev.name}</p><p className="mt-1 text-xs text-zinc-500">{ev.rows} × {ev.columns} · {ev.approved_count}/{ev.total_slots} filled</p></div><StatusPill status={ev.status}/></a>)}</div></div></main>}
export function StatusPill({status}:{status:Event['status']}){const c={draft:'bg-zinc-700/40 text-zinc-300',live:'bg-emerald-400/10 text-emerald-300',ended:'bg-red-400/10 text-red-300'}[status];return <span className={`rounded-full px-3 py-1 text-xs uppercase tracking-wider ${c}`}>{status}</span>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label><span className="text-xs text-zinc-500">{label}</span><input type="number" min="2" max="100" value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm"/></label>}
