'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {motion} from 'framer-motion';
import QRCode from 'qrcode';
import {demoSubmissions} from '@/lib/demo';
import type {Submission,WallData,WallTile} from '@/lib/types';
export default function MosaicWall({eventId,initial}:{eventId:string;initial?:WallData}){return initial?<LiveWall eventId={eventId} initial={initial}/>:<DemoWall eventId={eventId}/>}

function LiveWall({eventId,initial}:{eventId:string;initial:WallData}){const [data,setData]=useState(initial);const [qr,setQr]=useState('');
// Tiles already on screen at load appear instantly; only later arrivals fly in.
const onLoad=useRef(new Set(initial.tiles.map(t=>t.id)));
const refresh=useCallback(async()=>{try{const r=await fetch(`/api/wall/${eventId}`,{cache:'no-store'});if(r.ok)setData(await r.json())}catch{}},[eventId]);
// New photos appear within ~3 s: poll the wall API (paused while the tab is hidden).
useEffect(()=>{const tick=()=>{if(document.visibilityState==='visible')refresh()};const iv=setInterval(tick,3000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(iv);document.removeEventListener('visibilitychange',tick)}},[refresh]);
useEffect(()=>{QRCode.toDataURL(`${window.location.origin}/upload?event=${eventId}`,{width:320,margin:1}).then(setQr)},[eventId]);
const {event,tiles}=data;const total=event.rows*event.columns;const filled=tiles.length;const complete=filled>=total;const pct=Math.min(100,Math.round(filled/total*100));
const byIndex=useMemo(()=>{const m=new Map<number,WallTile>();for(const t of tiles)m.set(t.tile_index,t);return m},[tiles]);
const accent=event.accent_color||'#d8ff3e';
return <main className="relative min-h-screen overflow-hidden noise" style={{background:event.background||'#08090b'}}><div className="relative flex min-h-screen flex-col items-center justify-center p-6"><div className="mb-4 flex w-full items-end justify-between" style={{maxWidth:`min(100%, calc(80vh * ${event.columns} / ${event.rows}))`}}><div><p className="text-xs uppercase tracking-[.35em] text-zinc-500">LIVE MOSAIC</p><h1 className="mt-2 text-2xl font-semibold">{event.name}</h1></div><div className="text-right"><div className="text-sm font-medium">{filled} / {total} PHOTOS</div><div className="mt-1 text-xs text-zinc-500">{pct}% COMPLETE</div></div></div>
<div className="relative w-full overflow-hidden rounded-2xl border border-white/10 bg-black shadow-2xl" style={{aspectRatio:`${event.columns} / ${event.rows}`,maxWidth:`min(100%, calc(80vh * ${event.columns} / ${event.rows}))`}}><div className="absolute inset-0 grid" style={{gridTemplateColumns:`repeat(${event.columns},minmax(0,1fr))`,gridTemplateRows:`repeat(${event.rows},minmax(0,1fr))`}}>{Array.from({length:total},(_,i)=>{const t=byIndex.get(i);return <div key={i} className="overflow-hidden bg-zinc-950">{t&&<motion.img key={t.id} src={t.thumbnail_url} alt="" className="h-full w-full object-cover" initial={onLoad.current.has(t.id)?false:{opacity:0,scale:3}} animate={{opacity:1,scale:1}} transition={{duration:.9/(event.animation_speed||1),ease:[.22,1,.36,1]}}/>}</div>})}</div>
{event.target_image_url&&<motion.img src={event.target_image_url} alt="" className="pointer-events-none absolute inset-0 h-full w-full object-cover" initial={false} animate={{opacity:complete?.35:.55}} transition={{duration:2}}/>}
{complete&&<motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1}} className="absolute inset-0 grid place-items-center bg-black/20"><div className="text-center"><motion.p initial={{y:20}} animate={{y:0}} className="text-4xl font-semibold tracking-tight md:text-6xl" style={{textShadow:'0 4px 30px rgba(0,0,0,.7)'}}>{event.final_message||'WE DID IT TOGETHER'}</motion.p><p className="mt-3 text-sm uppercase tracking-[.35em] text-zinc-200">{total} moments · one picture</p></div></motion.div>}</div>
<div className="mt-4 h-1 w-full overflow-hidden rounded-full bg-white/10" style={{maxWidth:`min(100%, calc(80vh * ${event.columns} / ${event.rows}))`}}><motion.div className="h-full" style={{background:accent}} animate={{width:`${pct}%`}}/></div></div>
{qr&&!complete&&event.status==='live'&&<div className="absolute bottom-6 right-6 rounded-2xl bg-white p-3 text-center text-black shadow-2xl"><img src={qr} alt="Scan to add your photo" className="h-32 w-32"/><p className="mt-1 text-[11px] font-semibold uppercase tracking-wider">Scan to join</p></div>}</main>}

function DemoWall({eventId}:{eventId:string}){const [items,setItems]=useState<Submission[]>(()=>demoSubmissions(0,eventId));const [running,setRunning]=useState(false);const [speed,setSpeed]=useState(1);const [complete,setComplete]=useState(false);const timer=useRef<NodeJS.Timeout|null>(null);const total=750;
const startDemo=()=>{setItems([]);setComplete(false);setRunning(true)};
useEffect(()=>{if(!running)return;timer.current=setInterval(()=>setItems(prev=>{if(prev.length>=total){if(timer.current)clearInterval(timer.current);setRunning(false);setComplete(true);return prev}const n=prev.length;return [...prev,...demoSubmissions(1,eventId).map(x=>({...x,id:`demo-${n}`,tile_index:n}))]}),Math.max(40,180/speed));return()=>{if(timer.current)clearInterval(timer.current)}},[running,speed,eventId]);
const pct=Math.round(items.length/total*100);const cells=useMemo(()=>items.slice(-120),[items]);return <main className="relative min-h-screen overflow-hidden bg-[#08090b] noise"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(216,255,62,.08),transparent_45%)]"/><div className="relative flex min-h-screen flex-col items-center justify-center p-8"><div className="mb-5 flex w-full max-w-[1500px] items-end justify-between"><div><p className="text-xs uppercase tracking-[.35em] text-zinc-500">LIVE MOSAIC</p><h1 className="mt-2 text-2xl font-semibold">Digital Mosaic Wall</h1></div><div className="text-right"><div className="text-sm font-medium">{items.length} / {total} PHOTOS</div><div className="mt-1 text-xs text-zinc-500">{pct}% COMPLETE</div></div></div><div className="relative w-full max-w-[1500px] aspect-video overflow-hidden rounded-2xl border border-white/10 bg-black shadow-2xl"><div className="absolute inset-0 grid grid-cols-[repeat(15,minmax(0,1fr))] grid-rows-[repeat(8,minmax(0,1fr))] gap-[1px] p-2">{cells.map((s,i)=><motion.div key={s.id} initial={{opacity:0,scale:.5,x:(i%5-2)*80,y:(i%3-1)*50}} animate={{opacity:1,scale:1,x:0,y:0}} transition={{duration:Math.max(.25,.75/speed),ease:[.22,1,.36,1]}} className="overflow-hidden bg-zinc-900"><img src={s.thumbnail_url} alt="" className="h-full w-full object-cover"/></motion.div>)}</div><div className="absolute inset-0 pointer-events-none opacity-[.22] bg-[linear-gradient(90deg,transparent_49.9%,rgba(255,255,255,.12)_50%,transparent_50.1%),linear-gradient(0deg,transparent_49.9%,rgba(255,255,255,.12)_50%,transparent_50.1%)]"/>{complete&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="absolute inset-0 grid place-items-center bg-black/35 backdrop-blur-[2px]"><div className="text-center"><motion.p initial={{y:20}} animate={{y:0}} className="text-4xl font-semibold tracking-tight">WE DID IT TOGETHER</motion.p><p className="mt-3 text-sm uppercase tracking-[.35em] text-zinc-300">750 moments · one picture</p></div></motion.div>}</div><div className="mt-6 flex items-center gap-3"><button onClick={startDemo} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-black">{running?'Running demo…':'Start demo'}</button><button onClick={()=>setRunning(v=>!v)} className="rounded-full border border-zinc-700 px-5 py-2.5 text-sm">{running?'Pause':'Resume'}</button><label className="text-xs text-zinc-500">Speed <input aria-label="Animation speed" className="ml-2 align-middle" type="range" min=".5" max="3" step=".25" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label></div></div></main>}
