'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {motion,AnimatePresence} from 'framer-motion';
import {demoSubmissions} from '@/lib/demo';
import type {Submission} from '@/lib/types';
export default function MosaicWall({eventId}:{eventId:string}){const [items,setItems]=useState<Submission[]>(()=>demoSubmissions(0,eventId));const [running,setRunning]=useState(false);const [speed,setSpeed]=useState(1);const [complete,setComplete]=useState(false);const timer=useRef<NodeJS.Timeout|null>(null);const total=750;
const startDemo=()=>{setItems([]);setComplete(false);setRunning(true)};
useEffect(()=>{if(!running)return;timer.current=setInterval(()=>setItems(prev=>{if(prev.length>=total){if(timer.current)clearInterval(timer.current);setRunning(false);setComplete(true);return prev}const n=prev.length;return [...prev,...demoSubmissions(1,eventId).map(x=>({...x,id:`demo-${n}`,tile_index:n}))]}),Math.max(40,180/speed));return()=>{if(timer.current)clearInterval(timer.current)}},[running,speed,eventId]);
useEffect(()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!url||eventId==='demo')return;/* Production wiring lives in the API/DB layer; demo remains self-contained. */},[eventId]);
const pct=Math.round(items.length/total*100);const cells=useMemo(()=>items.slice(-120),[items]);return <main className="relative min-h-screen overflow-hidden bg-[#08090b] noise"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(216,255,62,.08),transparent_45%)]"/><div className="relative flex min-h-screen flex-col items-center justify-center p-8"><div className="mb-5 flex w-full max-w-[1500px] items-end justify-between"><div><p className="text-xs uppercase tracking-[.35em] text-zinc-500">LIVE MOSAIC</p><h1 className="mt-2 text-2xl font-semibold">Digital Mosaic Wall</h1></div><div className="text-right"><div className="text-sm font-medium">{items.length} / {total} PHOTOS</div><div className="mt-1 text-xs text-zinc-500">{pct}% COMPLETE</div></div></div><div className="relative w-full max-w-[1500px] aspect-video overflow-hidden rounded-2xl border border-white/10 bg-black shadow-2xl"><div className="absolute inset-0 grid grid-cols-[repeat(15,minmax(0,1fr))] grid-rows-[repeat(8,minmax(0,1fr))] gap-[1px] p-2">{cells.map((s,i)=><motion.div key={s.id} initial={{opacity:0,scale:.5,x:(i%5-2)*80,y:(i%3-1)*50}} animate={{opacity:1,scale:1,x:0,y:0}} transition={{duration:Math.max(.25,.75/speed),ease:[.22,1,.36,1]}} className="overflow-hidden bg-zinc-900"><img src={s.thumbnail_url} alt="" className="h-full w-full object-cover"/></motion.div>)}</div><div className="absolute inset-0 pointer-events-none opacity-[.22] bg-[linear-gradient(90deg,transparent_49.9%,rgba(255,255,255,.12)_50%,transparent_50.1%),linear-gradient(0deg,transparent_49.9%,rgba(255,255,255,.12)_50%,transparent_50.1%)]"/>{complete&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="absolute inset-0 grid place-items-center bg-black/35 backdrop-blur-[2px]"><div className="text-center"><motion.p initial={{y:20}} animate={{y:0}} className="text-4xl font-semibold tracking-tight">WE DID IT TOGETHER</motion.p><p className="mt-3 text-sm uppercase tracking-[.35em] text-zinc-300">750 moments · one picture</p></div></motion.div>}</div><div className="mt-6 flex items-center gap-3"><button onClick={startDemo} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-black">{running?'Running demo…':'Start demo'}</button><button onClick={()=>setRunning(v=>!v)} className="rounded-full border border-zinc-700 px-5 py-2.5 text-sm">{running?'Pause':'Resume'}</button><label className="text-xs text-zinc-500">Speed <input aria-label="Animation speed" className="ml-2 align-middle" type="range" min=".5" max="3" step=".25" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label></div></div></main>}
